name: gfeat
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - cmake
  - make
  - pybind11
  - matplotlib
  - cartopy
  - numpy  # optional, if your bindings use NumPy
  - compilers  # for C++ compiler
  - eigen
